### ISSUE TITLE
per_page=20000 is no longer supported

### ISSUE THREAD

**Issue by foice** [manuelamador/TimeSeries#1]
Hello, thanks for doing this parser for the API of Wolrd Bank data!

I noticed that your code queries the API requiring a large number of items per page, `per_page=20000`

This seems to be no longer supported and one has to go through the pages one by one. Do you think is easy to fix?

Thanks,
Roberto

**Comment by foice** [comment]
I think that this solves the problem

`(* indicatorsWB = Import["http://api.worldbank.org/indicator?per_page=200000", "XML"][[2, 3]]; *)
        pages = Read[
        StringToStream[
             "pages" /.Import["http://api.worldbank.org/indicator?per_page=10000", "XML"][[2, 2]]], Number];
        PrintTemporary["retrieving ",pages, " web pages"];
        indicatorsWB=Join[Table[Import["http://api.worldbank.org/indicator?per_page=10000&page=" <> ToString[page], "XML"][[2, 3]], {page, {1, pages}}]];
        Clear[pages];`

**Comment by manuelamador** [comment]
great. thanks. I'll be updating this then.
